//version 2.0.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: spot_instrument_service/proto/v2/spot_instrument_service.proto

package spot_instrument_service_proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	shared_proto "github.com/Megahhearz/proto/shared_proto/shared_proto/proto/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Market struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                    `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DeletedAt     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	AllowedRoles  []shared_proto.UserRole `protobuf:"varint,5,rep,packed,name=allowed_roles,json=allowedRoles,proto3,enum=user_role_proto.UserRole" json:"allowed_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Market) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Market) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Market) GetAllowedRoles() []shared_proto.UserRole {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

type ViewMarketsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserRoles     []shared_proto.UserRole `protobuf:"varint,1,rep,packed,name=user_roles,json=userRoles,proto3,enum=user_role_proto.UserRole" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsRequest) GetUserRoles() []shared_proto.UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescGZIP(), []int{2}
}

func (x *ViewMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ViewMarketsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ViewMarketsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ViewMarketsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ViewMarketsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_spot_instrument_service_proto_v2_spot_instrument_service_proto protoreflect.FileDescriptor

const file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDesc = "" +
	"\n" +
	">spot_instrument_service/proto/v2/spot_instrument_service.proto\x12\x1dspot_instrument_service_proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%shared_proto/proto/v2/user_role.proto\"\xd5\x01\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12>\n" +
	"\rallowed_roles\x18\x05 \x03(\x0e2\x19.user_role_proto.UserRoleR\fallowedRolesB\r\n" +
	"\v_deleted_at\"N\n" +
	"\x12ViewMarketsRequest\x128\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\x0e2\x19.user_role_proto.UserRoleR\tuserRoles\"\xc9\x01\n" +
	"\x13ViewMarketsResponse\x12?\n" +
	"\amarkets\x18\x01 \x03(\v2%.spot_instrument_service_proto.MarketR\amarkets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages2\x8d\x01\n" +
	"\x15SpotInstrumentService\x12t\n" +
	"\vViewMarkets\x121.spot_instrument_service_proto.ViewMarketsRequest\x1a2.spot_instrument_service_proto.ViewMarketsResponseBSZQgithub.com/Megahhearz/proto/spot_instrument_service;spot_instrument_service_protob\x06proto3"

var (
	file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescOnce sync.Once
	file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescData []byte
)

func file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescGZIP() []byte {
	file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescOnce.Do(func() {
		file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDesc), len(file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDesc)))
	})
	return file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDescData
}

var file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spot_instrument_service_proto_v2_spot_instrument_service_proto_goTypes = []any{
	(*Market)(nil),                // 0: spot_instrument_service_proto.Market
	(*ViewMarketsRequest)(nil),    // 1: spot_instrument_service_proto.ViewMarketsRequest
	(*ViewMarketsResponse)(nil),   // 2: spot_instrument_service_proto.ViewMarketsResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(shared_proto.UserRole)(0),    // 4: user_role_proto.UserRole
}
var file_spot_instrument_service_proto_v2_spot_instrument_service_proto_depIdxs = []int32{
	3, // 0: spot_instrument_service_proto.Market.deleted_at:type_name -> google.protobuf.Timestamp
	4, // 1: spot_instrument_service_proto.Market.allowed_roles:type_name -> user_role_proto.UserRole
	4, // 2: spot_instrument_service_proto.ViewMarketsRequest.user_roles:type_name -> user_role_proto.UserRole
	0, // 3: spot_instrument_service_proto.ViewMarketsResponse.markets:type_name -> spot_instrument_service_proto.Market
	1, // 4: spot_instrument_service_proto.SpotInstrumentService.ViewMarkets:input_type -> spot_instrument_service_proto.ViewMarketsRequest
	2, // 5: spot_instrument_service_proto.SpotInstrumentService.ViewMarkets:output_type -> spot_instrument_service_proto.ViewMarketsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_spot_instrument_service_proto_v2_spot_instrument_service_proto_init() }
func file_spot_instrument_service_proto_v2_spot_instrument_service_proto_init() {
	if File_spot_instrument_service_proto_v2_spot_instrument_service_proto != nil {
		return
	}
	file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDesc), len(file_spot_instrument_service_proto_v2_spot_instrument_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_instrument_service_proto_v2_spot_instrument_service_proto_goTypes,
		DependencyIndexes: file_spot_instrument_service_proto_v2_spot_instrument_service_proto_depIdxs,
		MessageInfos:      file_spot_instrument_service_proto_v2_spot_instrument_service_proto_msgTypes,
	}.Build()
	File_spot_instrument_service_proto_v2_spot_instrument_service_proto = out.File
	file_spot_instrument_service_proto_v2_spot_instrument_service_proto_goTypes = nil
	file_spot_instrument_service_proto_v2_spot_instrument_service_proto_depIdxs = nil
}
