//version 1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: shared_proto/proto/v2/user_role.proto

package user_role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_TRADER      UserRole = 1
	UserRole_USER_ROLE_ADMIN       UserRole = 2
	UserRole_USER_ROLE_VIEWER      UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_TRADER",
		2: "USER_ROLE_ADMIN",
		3: "USER_ROLE_VIEWER",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_TRADER":      1,
		"USER_ROLE_ADMIN":       2,
		"USER_ROLE_VIEWER":      3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_proto_v2_user_role_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_shared_proto_proto_v2_user_role_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_proto_v2_user_role_proto_rawDescGZIP(), []int{0}
}

var File_shared_proto_proto_v2_user_role_proto protoreflect.FileDescriptor

const file_shared_proto_proto_v2_user_role_proto_rawDesc = "" +
	"\n" +
	"%shared_proto/proto/v2/user_role.proto\x12\x0fuser_role_proto*f\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10USER_ROLE_TRADER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02\x12\x14\n" +
	"\x10USER_ROLE_VIEWER\x10\x03B4Z2github.com/Megahhearz/proto/shared_proto;user_roleb\x06proto3"

var (
	file_shared_proto_proto_v2_user_role_proto_rawDescOnce sync.Once
	file_shared_proto_proto_v2_user_role_proto_rawDescData []byte
)

func file_shared_proto_proto_v2_user_role_proto_rawDescGZIP() []byte {
	file_shared_proto_proto_v2_user_role_proto_rawDescOnce.Do(func() {
		file_shared_proto_proto_v2_user_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_proto_v2_user_role_proto_rawDesc), len(file_shared_proto_proto_v2_user_role_proto_rawDesc)))
	})
	return file_shared_proto_proto_v2_user_role_proto_rawDescData
}

var file_shared_proto_proto_v2_user_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_proto_v2_user_role_proto_goTypes = []any{
	(UserRole)(0), // 0: user_role_proto.UserRole
}
var file_shared_proto_proto_v2_user_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_proto_v2_user_role_proto_init() }
func file_shared_proto_proto_v2_user_role_proto_init() {
	if File_shared_proto_proto_v2_user_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_proto_v2_user_role_proto_rawDesc), len(file_shared_proto_proto_v2_user_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_proto_v2_user_role_proto_goTypes,
		DependencyIndexes: file_shared_proto_proto_v2_user_role_proto_depIdxs,
		EnumInfos:         file_shared_proto_proto_v2_user_role_proto_enumTypes,
	}.Build()
	File_shared_proto_proto_v2_user_role_proto = out.File
	file_shared_proto_proto_v2_user_role_proto_goTypes = nil
	file_shared_proto_proto_v2_user_role_proto_depIdxs = nil
}
